/* Generated By:JJTree&JavaCC: Do not edit this line. NavqParser.java */
package parser;

import java.io.*;
import java.util.Hashtable;
import java.util.Enumeration;
import java.util.ArrayList;

 import org.jgrapht.*;
    import org.jgrapht.alg.*;
    import org.jgrapht.graph.*;
    import java.util.List;


import java.net.*;

public class NavqParser/*@bgen(jjtree)*/implements NavqParserTreeConstants, NavqParserConstants {/*@bgen(jjtree)*/
  protected static JJTNavqParserState jjtree = new JJTNavqParserState();public static Hashtable ST = new Hashtable();




  public static void main(String args []) throws ParseException
  {
        String temp;
    STC    temp2;


    NavqParser parser = new NavqParser(System.in);

  try
    {

    SimpleNode root = parser.Start();
    root.dump("");
   }
   catch (ParseException e) {
                        System.out.println("Parse error: " + e);
                        return;
            }
    catch (TokenMgrError e) {
                        System.out.println("Token error: " + e);
                        return;
    }
     System.out.println("Successful parse");



         Enumeration t = ST.keys();

     while (t.hasMoreElements() == true) {

          temp = (String)t.nextElement();
          temp2 = (STC)ST.get(temp);
          System.out.println(temp);
          if ( temp2.type != null )
            System.out.println(" type = " + temp2.type);
          if ( temp2.value != null )
            System.out.println(" value = " + temp2.value);

    }

    List<String > graphdata = new ArrayList<String >();
    String filename = "./data/small.NY.gr";
    try
    {

            BufferedReader reader = new BufferedReader(new FileReader(filename));
            String line;
            while ((line = reader.readLine()) != null)
            {
                   graphdata.add(line);
            }
            reader.close();
          }
          catch (Exception e)
          {
            System.err.format("Exception occurred trying to read '%s'.", filename);
            e.printStackTrace();
          }



 SimpleDirectedWeightedGraph<String, DefaultWeightedEdge>  graph =
            new SimpleDirectedWeightedGraph<String, DefaultWeightedEdge>(DefaultWeightedEdge.class);
            graph.addVertex("v1");
            graph.addVertex("v2");
            graph.addVertex("v3");
            graph.addVertex("v4");
            graph.addVertex("v5");


            DefaultWeightedEdge e1 = graph.addEdge("v1", "v2");
            graph.setEdgeWeight(e1, 5);

            DefaultWeightedEdge e2 = graph.addEdge("v2", "v3");
            graph.setEdgeWeight(e2, 3);

            DefaultWeightedEdge e3 = graph.addEdge("v4", "v5");
            graph.setEdgeWeight(e3, 6);

            DefaultWeightedEdge e4 = graph.addEdge("v2", "v4");
            graph.setEdgeWeight(e4, 2);

            DefaultWeightedEdge e5 = graph.addEdge("v5", "v4");
            graph.setEdgeWeight(e5, 4);


            DefaultWeightedEdge e6 = graph.addEdge("v2", "v5");
            graph.setEdgeWeight(e6, 9);

            DefaultWeightedEdge e7 = graph.addEdge("v4", "v1");
            graph.setEdgeWeight(e7, 7);

            DefaultWeightedEdge e8 = graph.addEdge("v3", "v2");
            graph.setEdgeWeight(e8, 2);

            DefaultWeightedEdge e9 = graph.addEdge("v1", "v3");
            graph.setEdgeWeight(e9, 10);

            DefaultWeightedEdge e10 = graph.addEdge("v3", "v5");
            graph.setEdgeWeight(e10, 1);


            System.out.println("Shortest path from v1 to v5:");
            List shortest_path =   DijkstraShortestPath.findPathBetween(graph, "v1", "v5");
            System.out.println(shortest_path);
  }

  static final public SimpleNode Start() throws ParseException {
 /*@bgen(jjtree) START */
  SimpleNode jjtn000 = new SimpleNode(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      output();
           jjtree.closeNodeScope(jjtn000, true);
           jjtc000 = false;
          {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
  if (jjtc000) {
    jjtree.clearNodeScope(jjtn000);
    jjtc000 = false;
  } else {
    jjtree.popNode();
  }
  if (jjte000 instanceof RuntimeException) {
    {if (true) throw (RuntimeException)jjte000;}
  }
  if (jjte000 instanceof ParseException) {
    {if (true) throw (ParseException)jjte000;}
  }
  {if (true) throw (Error)jjte000;}
    } finally {
  if (jjtc000) {
    jjtree.closeNodeScope(jjtn000, true);
  }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void output() throws ParseException {
 /*@bgen(jjtree) OUTPUT */
  SimpleNode jjtn000 = new SimpleNode(JJTOUTPUT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OUTPUT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
        numberOfPaths();
        break;
      case PLACES:
        placesAtDistance();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void numberOfPaths() throws ParseException {
 /*@bgen(jjtree) NUMBER_OF_PATHS */
  SimpleNode jjtn000 = new SimpleNode(JJTNUMBER_OF_PATHS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      number();
      jj_consume_token(PATHS);
      jj_consume_token(FROM);
      places();
      jj_consume_token(DOUBLEPOINT);
      jj_consume_token(CRITERIA);
      jj_consume_token(DOUBLEPOINT);
      criteriaType();
    } catch (Throwable jjte000) {
  if (jjtc000) {
    jjtree.clearNodeScope(jjtn000);
    jjtc000 = false;
  } else {
    jjtree.popNode();
  }
  if (jjte000 instanceof RuntimeException) {
    {if (true) throw (RuntimeException)jjte000;}
  }
  if (jjte000 instanceof ParseException) {
    {if (true) throw (ParseException)jjte000;}
  }
  {if (true) throw (Error)jjte000;}
    } finally {
  if (jjtc000) {
    jjtree.closeNodeScope(jjtn000, true);
  }
    }
  }

  static final public void placesAtDistance() throws ParseException {
 /*@bgen(jjtree) PLACES_AT_DISTANCE */
  SimpleNode jjtn000 = new SimpleNode(JJTPLACES_AT_DISTANCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PLACES);
      jj_consume_token(WITH);
      jj_consume_token(DISTANCE);
      compareSign();
      number();
      jj_consume_token(PLACES);
      jj_consume_token(FROM);
      place();
    } catch (Throwable jjte000) {
  if (jjtc000) {
    jjtree.clearNodeScope(jjtn000);
    jjtc000 = false;
  } else {
    jjtree.popNode();
  }
  if (jjte000 instanceof RuntimeException) {
    {if (true) throw (RuntimeException)jjte000;}
  }
  if (jjte000 instanceof ParseException) {
    {if (true) throw (ParseException)jjte000;}
  }
  {if (true) throw (Error)jjte000;}
    } finally {
  if (jjtc000) {
    jjtree.closeNodeScope(jjtn000, true);
  }
    }
  }

  static final public void compareSign() throws ParseException {
 /*@bgen(jjtree) COMPARE_SIGN */
   SimpleNode jjtn000 = new SimpleNode(JJTCOMPARE_SIGN);
   boolean jjtc000 = true;
   jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(COMPARE);
               jjtree.closeNodeScope(jjtn000, true);
               jjtc000 = false;
              jjtn000.value = t.image;
 ST.put(t.image,new STC("compare_sign",t.image));
    } finally {
   if (jjtc000) {
     jjtree.closeNodeScope(jjtn000, true);
   }
    }
  }

  static final public void places() throws ParseException {
 /*@bgen(jjtree) TO */
  SimpleNode jjtn000 = new SimpleNode(JJTTO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      place();
      jj_consume_token(TO);
      place();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void place() throws ParseException {
 /*@bgen(jjtree) PLACE */
   SimpleNode jjtn000 = new SimpleNode(JJTPLACE);
   boolean jjtc000 = true;
   jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(QUOTED);
                jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
               jjtn000.value = t.image;
 ST.put(t.image,new STC("place",t.image));
    } finally {
   if (jjtc000) {
     jjtree.closeNodeScope(jjtn000, true);
   }
    }
  }

  static final public void number() throws ParseException {
 /*@bgen(jjtree) NUMBER */
   SimpleNode jjtn000 = new SimpleNode(JJTNUMBER);
   boolean jjtc000 = true;
   jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(NUMBER);
                jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
               jjtn000.value = t.image;
        ST.put(t.image,new STC("number",t.image));
    } finally {
   if (jjtc000) {
     jjtree.closeNodeScope(jjtn000, true);
   }
    }
  }

  static final public void criteriaType() throws ParseException {
 /*@bgen(jjtree) CRITERIA_TYPE */
  SimpleNode jjtn000 = new SimpleNode(JJTCRITERIA_TYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(CRITERIA_TYPE);
                      jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
                     jjtn000.value = t.image;
   ST.put(t.image,new STC("criteria",t.image));
    } finally {
  if (jjtc000) {
    jjtree.closeNodeScope(jjtn000, true);
  }
    }
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public NavqParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[1];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2020,};
   }

  /** Constructor with InputStream. */
  public NavqParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public NavqParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new NavqParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 1; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 1; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public NavqParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new NavqParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 1; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 1; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public NavqParser(NavqParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 1; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(NavqParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 1; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[20];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 1; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 20; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
