/* Generated By:JavaCC: Do not edit this line. NavqParserTreeConstants.java Version 5.0 */
package parser;

public interface NavqParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTOUTPUT = 1;
  public int JJTERROR_SKIPTO = 2;
  public int JJTNUMBEROFPATHS = 3;
  public int JJTPLACESATDISTANCE = 4;
  public int JJTCOMPARESIGN = 5;
  public int JJTPLACES = 6;
  public int JJTPLACE = 7;
  public int JJTNUMBER = 8;
  public int JJTCRITERIATYPE = 9;


  public String[] jjtNodeName = {
    "Start",
    "output",
    "error_skipto",
    "numberOfPaths",
    "placesAtDistance",
    "compareSign",
    "places",
    "place",
    "number",
    "criteriaType",
  };
}
/* JavaCC - OriginalChecksum=2c4a8bb95d7e567e0e78e257f3046620 (do not edit this line) */
