/* Generated By:JavaCC: Do not edit this line. NavqParserTreeConstants.java Version 5.0 */
package parser;

public interface NavqParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTOUTPUT = 1;
  public int JJTNUMBER_OF_PATHS = 2;
  public int JJTPLACES_AT_DISTANCE = 3;
  public int JJTPLACE = 4;
  public int JJTNUMBER = 5;
  public int JJTCRITERIA_TYPE = 6;


  public String[] jjtNodeName = {
    "START",
    "OUTPUT",
    "NUMBER_OF_PATHS",
    "PLACES_AT_DISTANCE",
    "PLACE",
    "NUMBER",
    "CRITERIA_TYPE",
  };
}
/* JavaCC - OriginalChecksum=c8714f493c246d757994c96cef7e2742 (do not edit this line) */
