/* Generated By:JavaCC: Do not edit this line. NavqParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NavqParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int CRITERIA_TYPE = 8;
  /** RegularExpression Id. */
  int QUOTES = 9;
  /** RegularExpression Id. */
  int OUTPUT = 10;
  /** RegularExpression Id. */
  int PATHS = 11;
  /** RegularExpression Id. */
  int PLACES = 12;
  /** RegularExpression Id. */
  int FROM = 13;
  /** RegularExpression Id. */
  int TO = 14;
  /** RegularExpression Id. */
  int CRITERIA = 15;
  /** RegularExpression Id. */
  int WITH = 16;
  /** RegularExpression Id. */
  int DISTANCE = 17;
  /** RegularExpression Id. */
  int COMPARE = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DIGIT>",
    "<STRING>",
    "<CRITERIA_TYPE>",
    "\"\\\"\"",
    "\"Output\"",
    "\"paths\"",
    "\"places\"",
    "\"from\"",
    "\"to\"",
    "\"criteria\"",
    "\"with\"",
    "\"distance\"",
    "<COMPARE>",
  };

}
