/* Generated By:JavaCC: Do not edit this line. NavqParserTreeConstants.java Version 5.0 */
package parser;

public interface NavqParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTOUTPUT = 1;
  public int JJTNUMBEROFPATHS = 2;
  public int JJTPLACESATDISTANCE = 3;
  public int JJTCOMPARESIGN = 4;
  public int JJTPLACES = 5;
  public int JJTPLACE = 6;
  public int JJTNUMBER = 7;
  public int JJTCRITERIATYPE = 8;


  public String[] jjtNodeName = {
    "Start",
    "output",
    "numberOfPaths",
    "placesAtDistance",
    "compareSign",
    "places",
    "place",
    "number",
    "criteriaType",
  };
}
/* JavaCC - OriginalChecksum=f452ce291e6bf2062c8bf6ac922ce593 (do not edit this line) */
